version: 2.1

jobs:
  build:
    docker:
      - image: node:lts-slim
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: |
            docker build -t p30205/express-server:0.0.5 -f docker/node/dockerfile .
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push p30205/express-server:0.0.5

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - add_ssh_keys:
          fingerprints:
            - $SSH_KEY_FINGER_PRINT
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@$AWS_IP << 'EOF'
            docker pull p30205/express-server
            docker stop express-server || true
            docker rm express-server || true
            docker run -d --name express-server -p 3000:3000 p30205/express-server
            EOF

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
