FROM node:14.17.0

ENV NODE_OPTIONS="--max-old-space-size=8192"

RUN mkdir -p express-server
COPY ./package.json /express-server/
COPY ./src /express-server/src

ENV NODE_ENV=production
ENV MYSQL_DATABASE_USERNAME=hank

WORKDIR /express-server
# RUN npm install pm2 -g
RUN npm install

CMD ["pm2-runtime", "start", "./src/index.js"]
