FROM node:lts-slim

RUN mkdir -p express-server
COPY ./package.json /express-server/
COPY ./src /express-server/src

ENV NODE_ENV=production
ENV MYSQL_DATABASE_USERNAME=hank

WORKDIR /express-server
# RUN npm install pm2 -g
RUN npm install --omit=dev

CMD ["pm2-runtime", "start", "./src/index.js"]
